## 配置文件

# pool: 182.92.163.225:3339
pool: 127.0.0.1:3339
# 1MzNY1oA3kfgYi75zquj3SRUPYztzXHzK9
# 158481337EtoFJnusXpbzoXUvXJubohmXz
# 1EDUeK8NAjrgYhgDFv9NJecn8dNyJJsu3y
# 1QJ8AQ6m6HCT3EPerjv22wJQNuDy9MVGWm



reward: 1CPut4fYB1vRQPgSPMYqmpvP4DJVP5mcsd
supervene: 3

